Cleaned up scripts.

diff --git a/scripts/typecheck b/scripts/typecheck
--- a/scripts/typecheck
+++ b/scripts/typecheck
@@ -1,15 +1,16 @@
 #!/bin/bash
 
-if [ $# -ne 1 ]; then
-	echo 'Usage: typecheck <cminor file>'
-	exit 2
-fi
-
-make >& /dev/null || exit 1
-CFFILE=$1
-echo "==== File $CFFILE ===="
-cat "$CFFILE"
-echo "==== ===="
-java cminor.Compiler -l "$CFFILE"
-echo "Return Code: $?"
+[ $# -eq 1 -a -f "$1" ] || { echo 'Usage: typecheck <cminor file>'; exit 1; }
+make && {
+	FIN=$1
+	echo "==== $FIN ===="
+	cat "$FIN"
+	echo "==== Result ===="
+	java cminor.Compiler -l "$FIN" && {
+		echo "Success"
+	} || {
+		echo "Failure"
+	}
+}
+exit $?
 
